### ISSUE TITLE
Valeurs restent inchangées à la fermeture du formspec

### ISSUE THREAD

**Issue by matt8fr** [MT-Eurythmia/magic-brush#1]
Par rapport aux magic staffs les clics sont inversés, gauche pour utiliser les magic staffs, droit pour la brush.
Et quand je tente de modifier les valeurs rien ne change, quand je ré-ouvre le formspec de réglages elles n'ont pas bougé.

**Comment by paly2** [comment]
> par rapport au magic staff les clique sont inverser, gauche pour utiliser les magic staff, droit pour le brush.

Oui c'est volontaire, je trouvais ça plus logique (clic droit = poser les blocs). Tu préfères un clic gauche ?

> quand je change les valeurs rien ne change, quand je veux re changer les valeurs c'est remis comme avant.

Bizarre, avec 0.4.16 dev je n'ai pas ce problème. Les valeurs restent inchangées quand tu fermes le formspec en appuyant sur Échap (sauf les deux checkboxes), il faut cliquer sur "Proceed" pour les enregistrer

**Comment by matt8fr** [comment]
Pour le clic ça va je vais m'y faire !
Je suis en 0.4.16 stable.
Peu importe ce que je fais, les valeurs restent inchangées.

**Comment by paly2** [comment]
J'ai vu que tu avais fait un commit sur le dépôt dans lequel tu modifiais partiellement le nom de la brosse en `magic_brush:brush`. J'ai annulé ce commit car le nom du mod est bien `brush`, et j'ai ajouté un fichier `mod.conf` pour que le mod puisse fonctionner quel que soit le nom du dossier dans lequel il se trouve.

Es-tu certain de tester le mod après l'annulation de ce commit ? En effet, celui-ci empêchait les valeurs d'être modifiées à la fermeture du formspec (une erreur "You must hold the brush." était sytématiquement affichée), et pouvait aussi empêcher le formspec de s'ouvrir.

**Comment by matt8fr** [comment]
le jeu crasher sans ma modif, avec le mod.conf le mod fonctionne parfaitement. 😄 
il y avait bien "You must hold the brush."
